# Exp 5-1에서 Cosine similarity dimension 오류 확인, 다시 실행

model: MyLinearNetv2
trainfunc: CS

batch_size: 1000
max_epoch: 40
test_interval: 1
nDataLoaderThread: 5
activation: ELU

lr_decay: 0.99
lr: 0.00001

train_list: data/trainset_normal_list.txt
valid_list: data/testset_normal_list.txt
test_list: data/testset_test_list.txt
test_list_libri: data/libriset_test_list.txt

train_path: /home/doyeolkim/vox_emb/train/
valid_path: /home/doyeolkim/vox_emb/test/ 
test_path: /home/doyeolkim/vox_emb/test/
test_path_libri: /home/doyeolkim/libri_emb/valid2/

# gen_list: data/trainset_normal_list.txt
# gen_path: /home/doyeolkim/vox_emb/train/
# gen_target_dir: emb_train

gen_list: data/testset_normal_list.txt
gen_path: /home/doyeolkim/vox_emb/test/
gen_target_dir: emb_test

multiple_embedding_flag: C