# multiple embedding flag type C 테스트

model: MyLinearNetv4
trainfunc: MSE

batch_size: 200
max_epoch: 40
test_interval: 1
nDataLoaderThread: 5
activation: ELU

lr_decay: 0.99
lr: 0.00001

train_list: data/train_list.txt
valid_list: data/valid_list.txt
test_list: data/test_list.txt

train_path: /home/doyeolkim/vox_emb/train/
valid_path: /home/doyeolkim/vox_emb/test/ 
test_path: /home/doyeolkim/vox_emb/test/

multiple_embedding_flag: C